# serverless.yml

service: sls-node-express

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  profile: childbamboo

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
